# Generated by Django 3.2.17 on 2023-02-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('deptName_id', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('email_id', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_names', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('deptName', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('email_id', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Lname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email_id', models.CharField(max_length=50)),
                ('blood_gp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='todayPatList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtoms', models.CharField(max_length=50)),
                ('token_number', models.IntegerField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=50)),
                ('nurseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email_id', models.CharField(max_length=50)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='pharm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email_id', models.CharField(max_length=50)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='mystatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_on', models.CharField(max_length=50)),
                ('not_available_at', models.TimeField()),
                ('op_time', models.TimeField()),
                ('no_patient_fornoon', models.IntegerField()),
                ('no_patient_afternoon', models.IntegerField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=50)),
                ('medicine_dosage', models.CharField(max_length=50)),
                ('bill_amount', models.CharField(max_length=50)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient')),
                ('pharmasistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.pharm')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.login'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField()),
                ('reg_time', models.TimeField()),
                ('token_number', models.IntegerField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient')),
            ],
        ),
    ]
