# Generated by Django 3.2.17 on 2023-03-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='nurseid',
        ),
    ]
