# Generated by Django 3.2.17 on 2023-03-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0004_patlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patlist',
        ),
    ]
