# Generated by Django 3.2.17 on 2023-03-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0006_patlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patlist',
            name='blood_gp',
        ),
        migrations.RemoveField(
            model_name='patlist',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patlist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patlist',
            name='patName',
        ),
        migrations.RemoveField(
            model_name='patlist',
            name='patientid',
        ),
    ]
