# Generated by Django 3.2.17 on 2023-03-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0007_auto_20230320_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patlist',
            name='Status',
        ),
    ]
