# Generated by Django 3.2.17 on 2023-03-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0008_remove_patlist_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patlist',
        ),
    ]
