# Generated by Django 3.2.17 on 2023-03-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0017_auto_20230321_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patlist',
        ),
    ]
