# Generated by Django 3.2.17 on 2023-03-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0019_patlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patlist',
            name='doctorid',
        ),
    ]
