# Generated by Django 3.2.17 on 2023-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0027_auto_20230321_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='todayPatList',
        ),
    ]
