# Generated by Django 3.2.17 on 2023-03-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0028_auto_20230321_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientList',
        ),
    ]
