# Generated by Django 3.2.17 on 2023-03-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0030_patlist_todaypatlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todayPatList',
        ),
    ]
