# Generated by Django 3.2.17 on 2023-03-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0033_remove_patlist_patientid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patlist',
        ),
    ]
