# Generated by Django 3.2.17 on 2023-03-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0034_delete_patlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='patlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=50)),
                ('medicine_names', models.CharField(max_length=50)),
                ('medicine_dosage', models.CharField(max_length=50)),
            ],
        ),
    ]
