# Generated by Django 3.2.17 on 2023-03-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0035_patlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patlist',
        ),
    ]
