# Generated by Django 3.2.17 on 2023-03-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0036_delete_patlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='patlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_dosage', models.CharField(max_length=50)),
                ('NoTablet', models.CharField(max_length=50)),
                ('issueDate', models.DateField()),
                ('expDate', models.DateField()),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.doctor')),
                ('medicine_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.med')),
                ('nurseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.nurse')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.patient')),
                ('pharmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.pharm')),
                ('testName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.test')),
            ],
        ),
    ]
