# Generated by Django 3.2.17 on 2023-04-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0038_auto_20230402_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='pattlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medcine_dosage', models.CharField(max_length=50)),
                ('NoTablet', models.CharField(max_length=50)),
                ('issueDate', models.DateField()),
                ('expDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='patlist',
        ),
    ]
