


from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.main,name="fp"),
     path('login', views.loginn, name="login"),
     path('nursehome',views.nursehome,name="nursehome"),
     path('Dochome',views.Dochome,name="Dochome"),
     path('pharmhome',views.pharmhome,name="pharmhome"),
     path('Receptionisthome',views.Receptionisthome,name="Receptionisthome"),
     path('nurseTodayWork',views.nurseTodayWork,name="nurseTodayWork"),
     path('availableTest',views.availableTest,name="availableTest"),
     path('todayPatList',views.todayPatList,name="todayPatList"),
     path('searchPatient',views.searchPatient,name="searchPatient"),
     path('myStatusD',views.myStatusD,name="myStatusD"),
     # path('myStatus/<int:id>',views.myStatus,name="myStatus"),
     path('pharmTodayWork',views.pharmTodayWork,name="pharmTodayWork"),
     path('availableMedicine',views.availableMedicine,name="availableMedicine"),
     path('patientRegistration',views.patientRegistration,name="patientRegistration"),
     path('booking',views.bookingg,name="booking"),
     path('viewpat/<int:id>',views.viewpat,name="viewpat"),
     path('recepDoctor',views.recepDoctor,name="recepDoctor"),
     path('report',views.report,name="report"),
     path('testname',views.testname,name="testname"),
     path('medicinename', views.medicinename, name="medicinename"),
     path('deletetest/<int:id>',views.deletetest,name="deletetest"),
     path('deletemedicine', views.deletemedicine, name="deletemedicine"),
     path('docname', views.docname, name="docname"),
     path('addnurse', views.addnurse, name="addnurse"),
     path('addpharm', views.addpharm, name="addpharm"),
     path('addreceptionist', views.addreceptionist, name="addreceptionist"),
     path('adddoc', views.adddoc, name="adddoc"),
     path('viewallpat', views.viewallpat, name="viewallpat"),
     path('viewpat', views.viewpat, name="viewpat"),
     path('regdoc', views.regdoc, name="regdoc"),
     path('regpharm', views.regpharm, name="regpharm"),
     path('regnurse', views.regnurse, name="regnurse"),
     path('regrecep', views.regrecep, name="regrecep"),
     path('docdetail', views.docdetail, name="docdetail"),
     path('editpharm/<int:id>', views.editpharm, name="editpharm"),
     path('inserteditpharm', views.inserteditpharm, name="inserteditpharm"),
     path('Adminhomes', views.Adminhomes, name="Adminhomes"),
     path('editdoc/<int:id>', views.editdoc, name="editdoc"),
     path('editnurse/<int:id>', views.editnurse, name="editnurse"),
     path('editrecep/<int:id>', views.editrecep, name="editrecep"),
     path('inserteditdoc',views.inserteditdoc,name="inserteditdoc"),
     path('inserteditnurse',views.inserteditnurse,name="inserteditnurse"),
     path('insertbooking',views.insertbooking,name="insertbooking"),
     path('insertregnurse', views.insertregnurse, name="insertregnurse"),
     path('insertpatList', views.insertpatList, name="insertpatList"),
     path('addMedicines', views.addMedicines, name="addMedicines"),
     path('insertregrecep', views.insertregrecep, name="insertregrecep"),
     path('insertregpharm', views.insertregpharm, name="insertregpharm"),
     path('inserteditrecep', views.inserteditrecep, name="inserteditrecep"),
     path('insertregdoc',views.insertregdoc,name="insertregdoc"),
     path('insertregpat',views.insertregpat,name="insertregpat"),
     path('insertmyStatus', views.insertmyStatus, name="insertmyStatus"),
     path('deleterecep/<int:id>', views.deleterecep, name="deleterecep"),
     path('deletemedicine/<int:id>', views.deletemedicine, name="deletemedicine"),
     path('deletedoc/<int:id>', views.deletedoc, name="deletedoc"),
     path('deletenurse/<int:id>', views.deletenurse, name="deletenurse"),
     path('inserttestname', views.inserttestname, name="inserttestname"),
     path('logout',views.logout, name="logout"),

]

